version: "3.9"

volumes:
  frontend_portfolio_node_modules:

services:
  frontend:
    build:
      context: ./frontend/
      target: dev
    tty: true
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - frontend_node_modules:/app/frontend/node_modules
